### PR TITLE
Use execFile instead of spawn

### PR DESCRIPTION
**Pull request by osztenkurden**
I have only Windows machine, so could test it on windows only - using execFile instead of spawn doesn't make difference when using it from my testing, and allows the package to be used inside Electron easily

### CODE REVIEW

**Comment by sancarn** [comment]
Hi there, I haven’t yet had a chance to look into this myself.

what do you mean by “allows the package to be used in electron” - we are using it ourselves in LaunchMenu without issue.

**Comment by osztenkurden** [comment]
While development version of my app works fine, after compilation the electron app can't find and execute the .exe file inside asar package. I believe its about this issue https://github.com/electron/electron/issues/3512#issuecomment-158263808. It is possible to get around it with asarUnpack properties, however when I changed `spawn` to `execFile` it just clicked and worked.

**Comment by osztenkurden** [comment]
Before this PR will be forgotten I'd like to mention the `maxBuffer` issue. In my repo I set it to `Infinity` with great success and never noticed anything not working. Should I open another PR for this?

**Comment by sancarn** [comment]
> Before this PR will be forgotten I'd like to mention the `maxBuffer` issue. In my repo I set it to `Infinity` with great success and never noticed anything not working. Should I open another PR for this?

Yes please!

**Pull request merged**
